#!/usr/bin/env ruby

require "pre_push"

class Executor
	include PrePush
	### change only if you change your test runner
	@test_runner = {runner}
	###

	@solution = {sln_path} # the path to the solution to build
	@assemblies = {dtt} # insert dlls to test if different to the solution.
end

Executor.run