#!/usr/bin/env ruby

require "pre_push"

class Executor
	include PrePush
	### change only if you change your test runner
	@test_runner = {runner}
	###

	@solution = {sln_path} # the path to the solution to build
	# @assemblies = {test_dlls} # insert dlls to test if different to the solution.
	# override_msbuild 'path/to/custom/msbuild.exe'
end

Executor.run